apiVersion: v1	
kind: Service	
metadata:	
  name: guestbook-ui	
spec:	
  type: NodePort
  ports:	
  - port: 80	
    targetPort: 80	
    nodePort: 30081
  selector:	
    app: guestbook-ui
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-test
  namespace: tekton-pipelines
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /guestbook/?(.*)
        backend:
          serviceName: guestbook-ui
          servicePort: 80
